In [71]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [72]:
df = pd.read_csv('/content/Data.csv')

In [73]:
df

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [74]:
df.isna().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [75]:
df.shape

(10, 4)

In [76]:
df.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [77]:
map_column= {'Yes': 'Y', 'No': 'N'}

In [78]:
df['Purchased'] = df['Purchased'].map(map_column)

In [79]:
df

   Country   Age   Salary Purchased
0   France  44.0  72000.0         N
1    Spain  27.0  48000.0         Y
2  Germany  30.0  54000.0         N
3    Spain  38.0  61000.0         N
4  Germany  40.0      NaN         Y
5   France  35.0  58000.0         Y
6    Spain   NaN  52000.0         N
7   France  48.0  79000.0         Y
8  Germany  50.0  83000.0         N
9   France  37.0  67000.0         Y

In [80]:
df['Salary'].fillna(df['Salary'].mean(), inplace = True)

In [81]:
df

   Country   Age        Salary Purchased
0   France  44.0  72000.000000         N
1    Spain  27.0  48000.000000         Y
2  Germany  30.0  54000.000000         N
3    Spain  38.0  61000.000000         N
4  Germany  40.0  63777.777778         Y
5   France  35.0  58000.000000         Y
6    Spain   NaN  52000.000000         N
7   France  48.0  79000.000000         Y
8  Germany  50.0  83000.000000         N
9   France  37.0  67000.000000         Y

In [82]:
df['Age'].fillna(df['Age'].median(), inplace = True)

In [83]:
df

   Country   Age        Salary Purchased
0   France  44.0  72000.000000         N
1    Spain  27.0  48000.000000         Y
2  Germany  30.0  54000.000000         N
3    Spain  38.0  61000.000000         N
4  Germany  40.0  63777.777778         Y
5   France  35.0  58000.000000         Y
6    Spain  38.0  52000.000000         N
7   France  48.0  79000.000000         Y
8  Germany  50.0  83000.000000         N
9   France  37.0  67000.000000         Y

In [84]:
x = df.iloc[ :, :-1].values
y = df.iloc[ : , -1].values

In [85]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.0, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [95]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct= ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')

x = np.array(ct.fit_transform(x))

In [96]:
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.0, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [105]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [106]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [107]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [108]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.2, random_state=0 )

In [109]:
x_train, x_test, y_train, y_test

(array([[0.0, 1.0, 0.0, 40.0, 63777.77777777778],
        [1.0, 0.0, 0.0, 37.0, 67000.0],
        [0.0, 0.0, 1.0, 27.0, 48000.0],
        [0.0, 0.0, 1.0, 38.0, 52000.0],
        [1.0, 0.0, 0.0, 48.0, 79000.0],
        [0.0, 0.0, 1.0, 38.0, 61000.0],
        [1.0, 0.0, 0.0, 44.0, 72000.0],
        [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object),
 array([[0.0, 1.0, 0.0, 30.0, 54000.0],
        [0.0, 1.0, 0.0, 50.0, 83000.0]], dtype=object),
 array([1, 1, 1, 0, 1, 0, 0, 1]),
 array([0, 0]))

In [110]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

x_train[:, 3:] = sc.fit_transform(x_train [:, 3:])

x_test[:, 3:] = sc.fit_transform(x_test [:, 3:])

In [111]:
x_train

array([[0.0, 1.0, 0.0, 0.27978023533368457, 0.1238147854838185],
       [1.0, 0.0, 0.0, -0.23673712220542542, 0.4617563176278856],
       [0.0, 0.0, 1.0, -1.958461647335792, -1.5309334063940294],
       [0.0, 0.0, 1.0, -0.06456466969238875, -1.1114197802841526],
       [1.0, 0.0, 0.0, 1.6571598554379778, 1.7202971959575162],
       [0.0, 0.0, 1.0, -0.06456466969238875, -0.16751412153692966],
       [1.0, 0.0, 0.0, 0.9684700453858313, 0.9861483502652316],
       [1.0, 0.0, 0.0, -0.5810820272314987, -0.48214934111933727]],
      dtype=object)

In [112]:
df = pd.read_csv('/content/Data3.csv')

In [113]:
df

   Country   Age   Salary Most_Freq Constant Purchased
0   France  44.0  72000.0      Pune    India        No
1    Spain  27.0  48000.0      Pune    India       Yes
2  Germany  30.0  54000.0    Mumbai    India        No
3    Spain  38.0  61000.0      Pune    India        No
4  Germany  40.0      NaN      Pune    India       Yes
5   France  35.0  58000.0    Nagpur    India       Yes
6    Spain   NaN  52000.0      Pune    India        No
7   France  48.0  79000.0       NaN    India       Yes
8  Germany  50.0  83000.0    Mumbai    India        No
9   France  37.0  67000.0      Pune      NaN       Yes

In [134]:
df.shape

(10, 6)

In [135]:
df.isna().sum()

Country      0
Age          0
Salary       0
Most_Freq    1
Constant     1
Purchased    0
dtype: int64

In [136]:
from sklearn.impute import SimpleImputer
imputer_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer_median = SimpleImputer(missing_values=np.nan, strategy='median')
imputer_most_frequent = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer_cost= SimpleImputer(missing_values= np.nan, strategy= 'constant', fill_value = 'India')

In [137]:
df['Age']= imputer_mean.fit_transform(df[['Age']])

In [138]:
df['Salary'] = imputer_median.fit_transform(df[['Salary']])

In [140]:
 x = df.iloc[:, :-1].values
 y = df.iloc[:, -1].values

In [141]:
x

array([['France', 44.0, 72000.0, 'Pune', 'India'],
       ['Spain', 27.0, 48000.0, 'Pune', 'India'],
       ['Germany', 30.0, 54000.0, 'Mumbai', 'India'],
       ['Spain', 38.0, 61000.0, 'Pune', 'India'],
       ['Germany', 40.0, 61000.0, 'Pune', 'India'],
       ['France', 35.0, 58000.0, 'Nagpur', 'India'],
       ['Spain', 38.77777777777778, 52000.0, 'Pune', 'India'],
       ['France', 48.0, 79000.0, nan, 'India'],
       ['Germany', 50.0, 83000.0, 'Mumbai', 'India'],
       ['France', 37.0, 67000.0, 'Pune', nan]], dtype=object)

In [142]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [143]:
x[:, 3:4] = imputer_most_frequent.fit_transform (x[:, 3:4])

In [144]:
x[:, 4:5] = imputer_cost.fit_transform (x[:, 4:5])

In [145]:
x

array([['France', 44.0, 72000.0, 'Pune', 'India'],
       ['Spain', 27.0, 48000.0, 'Pune', 'India'],
       ['Germany', 30.0, 54000.0, 'Mumbai', 'India'],
       ['Spain', 38.0, 61000.0, 'Pune', 'India'],
       ['Germany', 40.0, 61000.0, 'Pune', 'India'],
       ['France', 35.0, 58000.0, 'Nagpur', 'India'],
       ['Spain', 38.77777777777778, 52000.0, 'Pune', 'India'],
       ['France', 48.0, 79000.0, 'Pune', 'India'],
       ['Germany', 50.0, 83000.0, 'Mumbai', 'India'],
       ['France', 37.0, 67000.0, 'Pune', 'India']], dtype=object)

In [149]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [150]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [154]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0, 3, 4])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [155]:
x

array([[1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 40.0, 61000.0],
       [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 37.0, 67000.0]], dtype=object)

In [156]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x[:, 7:] = sc.fit_transform(x[:, 7:])

In [157]:
x

array([[1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.758874361590019,
        0.7725676677947168],
       [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, -1.7115038793306814,
        -1.4087998648021307],
       [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, -1.2755547779917342,
        -0.8634579816529188],
       [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, -0.1130238410878753,
        -0.22722578464550494],
       [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.17760889313808945,
        -0.22722578464550494],
       [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, -0.5489729424268225,
        -0.4998967262201109],
       [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, -1.0452386093693227],
       [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.3401398300419485,
        1.4087998648021307],
       [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.6307725642679132,
        1.7723611202349385],
       [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, -0.2583402082008577,
        0.3181160985037069]], dtype=object)

In [158]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state= 1)